/**
 * Converted from Python: core/internet/generated_content_detection_engine.py
 * @generated — WebWeaveX python→javascript library port
 */

import * as py from "../runtime/pyCompat.js";

let _MARKERS: any = ["as an ai", "language model", "i cannot browse", "generated by ai", "auto-generated"];
export function detectGeneratedContent(text: any): any {
  var lower: any = String(py.or2(text, () => (""))).toLowerCase();
  var hits: any = py.iter(_MARKERS).filter((m: any) => py.contains(lower, m)).map((m: any) => m);
  var score: any = py.min([py.F(1.0), py.mul(py.len(hits), py.F(0.25))]);
  return {"generated_score": py.round(score, 3), "markers": hits, "likely_generated": (score >= py.F(0.5))};
}
