from __future__ import annotations

from typing import Dict


_MARKERS = (
    "as an ai",
    "language model",
    "i cannot browse",
    "generated by ai",
    "auto-generated",
)


def detect_generated_content(text: str) -> Dict[str, object]:
    lower = (text or "").lower()
    hits = [m for m in _MARKERS if m in lower]
    score = min(1.0, len(hits) * 0.25)
    return {"generated_score": round(score, 3), "markers": hits, "likely_generated": score >= 0.5}
