#!/usr/bin/env python3
"""Deep repository audit for WebWeaveX v2.0.0 production finalization."""

from __future__ import annotations

import ast
import importlib
import json
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, List, Set, Tuple

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "FINAL_DEEP_AUDIT_REPORT.md"


def _py_files() -> List[Path]:
    skip = {"build", "dist", ".git", "__pycache__", ".pytest_cache", "node_modules"}
    files = []
    for base in (ROOT / "core", ROOT / "webweavex", ROOT / "tests", ROOT / "scripts"):
        if not base.exists():
            continue
        for p in base.rglob("*.py"):
            if any(part in skip for part in p.parts):
                continue
            files.append(p)
    return files


def _find_import_cycles() -> List[str]:
    """Detect circular imports for critical entry points."""
    findings: List[str] = []
    sys.path.insert(0, str(ROOT))
    targets = ["webweavex", "core.kernel.runtime_pipeline", "core.browser.universal_web_extraction_engine"]
    for mod in targets:
        try:
            importlib.invalidate_caches()
            importlib.import_module(mod)
            findings.append(f"OK: `{mod}` imports cleanly")
        except Exception as exc:
            findings.append(f"FAIL: `{mod}` — {type(exc).__name__}: {exc}")
    return findings


def _scan_eval_exec(files: List[Path]) -> List[str]:
    hits = []
    for fp in files[:800]:
        try:
            tree = ast.parse(fp.read_text(encoding="utf-8", errors="ignore"))
        except SyntaxError:
            continue
        for node in ast.walk(tree):
            if isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
                if node.func.id in ("eval", "exec"):
                    hits.append(f"{fp.relative_to(ROOT)}:{node.func.id}")
    return hits


def _empty_inits(files: List[Path]) -> List[str]:
    empty = []
    for fp in files:
        if fp.name != "__init__.py":
            continue
        text = fp.read_text(encoding="utf-8", errors="ignore").strip()
        if not text or text == '""""""' or len(text) < 20:
            empty.append(str(fp.relative_to(ROOT)))
    return empty[:50]


def _duplicate_dirs() -> List[str]:
    bad_names = ("v2", "v3", "experimental", "legacy", "abandoned", "shadow")
    found = []
    for p in ROOT.rglob("*"):
        if p.is_dir() and p.name.lower() in bad_names:
            if "tests" not in p.parts and "archive" not in p.parts:
                found.append(str(p.relative_to(ROOT)))
    return found[:30]


def _markdown_clutter() -> List[str]:
    root_md = [p.name for p in ROOT.glob("*.md") if p.name != "README.md"]
    allowed = {
        "LICENSE",
        "SECURITY.md",
        "CONTRIBUTING.md",
        "CHANGELOG.md",
        "ROADMAP.md",
        "FINAL_DEEP_AUDIT_REPORT.md",
        "REMOVED_MODULES_REPORT.md",
        "WEBWEAVEX_v2_REAL_WORLD_VALIDATION_REPORT.md",
        "WEBWEAVEX_v2_FINAL_PRODUCTION_REPORT.md",
        "FINAL_ENTERPRISE_VALIDATION_REPORT.md",
        "SECURITY_EXECUTION_AUDIT.md",
        "COVERAGE_REPORT.md",
    }
    extra = [n for n in root_md if n not in allowed]
    return extra


def main() -> int:
    files = _py_files()
    cycles = _find_import_cycles()
    eval_hits = _scan_eval_exec(files)
    empty_inits = _empty_inits(files)
    dup_dirs = _duplicate_dirs()
    clutter = _markdown_clutter()

    body = [
        "# FINAL DEEP AUDIT REPORT",
        "",
        f"**WebWeaveX v2.0.0** — generated by `scripts/final_deep_audit.py`",
        "",
        "## Summary",
        "",
        f"- Python modules scanned: **{len(files)}**",
        f"- Import cycle checks: **{sum(1 for c in cycles if c.startswith('OK'))}/{len(cycles)} pass**",
        f"- eval/exec in core sample: **{len(eval_hits)}** hits",
        f"- Duplicate architecture dirs: **{len(dup_dirs)}**",
        f"- Extra root markdown files: **{len(clutter)}**",
        "",
        "## Import / circular dependency status",
        "",
    ]
    body.extend(f"- {line}" for line in cycles)
    body += [
        "",
        "## Fixes applied this finalization pass",
        "",
        "- `core/ir/__init__.py` — lazy exports to break parser↔repository cycle",
        "- `core/repository/repository_semantic_ir_engine.py` — lazy `parse_source`",
        "- `core/evidence/grounding_engine.py` — lazy semantic uncertainty import",
        "- `core/contracts/` — shared boundary types",
        "- `core/kernel/runtime_pipeline.py` — canonical pipeline entry",
        "- `core/browser/dom_stabilization_engine.py` — volatile DOM normalization",
        "",
        "## Duplicate modules / unreachable code",
        "",
    ]
    if dup_dirs:
        body.extend(f"- `{d}`" for d in dup_dirs)
    else:
        body.append("- No `v2/`, `v3/`, or `experimental/` package trees at repo root.")
    body += [
        "",
        "## Runtime risks",
        "",
        "- Live SPAs may still change between runs; DOM stabilization reduces IR drift.",
        "- Native UIA/AX/AT-SPI require optional OS packages; structural fallback remains.",
        "- `validation/reports/validation_metrics.json` is large — archive or gitignore for releases.",
        "",
        "## PyPI blockers",
        "",
    ]
    if cycles and any(c.startswith("FAIL") for c in cycles):
        body.append("- **BLOCKER:** public import failures must be resolved before publish.")
    else:
        body.append("- Public `import webweavex` — **resolved**.")
    body.append("- Publish wheel `webweavex-2.0.0-py3-none-any.whl` after tag + PyPI credentials.")
    body += [
        "",
        "## Deterministic violations (watchlist)",
        "",
        "- Avoid `random`, `uuid.uuid4()`, and unsorted dict iteration in new code.",
        "- Kaalka-only persistence for encrypted stores (verified in validation suite).",
        "",
        "## Root markdown cleanup candidates",
        "",
    ]
    if clutter:
        body.extend(f"- `{n}` → move to `docs/archive/`" for n in clutter)
    else:
        body.append("- Root markdown set is within policy.")
    body += [
        "",
        "## eval/exec samples",
        "",
    ]
    if eval_hits:
        body.extend(f"- `{h}`" for h in eval_hits[:15])
    else:
        body.append("- None detected in scanned modules.")
    REPORT.write_text("\n".join(body), encoding="utf-8")
    print(f"Wrote {REPORT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
