/**
 * WebWeaveX JavaScript public API surface.
 *
 * @generated by tools/convergence/build_public_api.py — conforms to the
 * same specification as the Python `webweavex` package public API
 * (origin/python:webweavex/__init__.py __all__). Hand-edit the generator,
 * not this file. Re-exports resolve to certified `src/` implementations.
 */
import { ingestInput } from "./ingestion/universalIngestionEngine.js";
import { extractPdfText } from "./files/pdfExtractionEngine.js";
import { extractDocxText } from "./files/docxExtractionEngine.js";
import { extractMultimodal as _extractMultimodal } from "./multimodal/universalMultimodalExtractionEngine.js";
import { extractArchive } from "./archive/archiveExtractionEngine.js";
import { extractHtmlFile } from "./files/htmlFileExtractionEngine.js";
import { compileMediaIr } from "./ir/mediaIr.js";
import { extractRepository as _extractRepositoryPath } from "./repository/universalRepositoryExtractionEngine.js";
import { extract as _extract } from "./extract/pipeline.js";
import { crawl as _crawl } from "./crawling/crawlerEngine.js";
import { analyzeGraph } from "./intelligence/graphAnalyzer.js";
import { queryGraph as _queryGraphIr } from "./query/graphQueryEngine.js";
import { queryDocuments as _queryDocumentIr } from "./query/documentQueryEngine.js";
import { queryKnowledge as _queryKnowledgeIr } from "./query/ontologyQueryEngine.js";
import { queryRepository as _queryRepositoryIr } from "./query/repositoryQueryEngine.js";
import { compileDocumentIr } from "./ir/documentIr.js";
import { compileRepositoryIr } from "./ir/repositoryIr.js";

/* ---- re-exported certified implementations (spec-equivalent names) ---- */

export { healSelector, loadAdaptiveMemory, recoverModalRuntime, saveAdaptiveMemory } from "./adaptive/index.js";
export { executeRuntimeObjective, loadApplicationMemory, runApplicationCognition, saveApplicationMemory } from "./application/index.js";
export { authenticateRuntime } from "./auth/index.js";
export { loadCausalMemory, replayCausalRuntime, runCausalityForExtraction, runCausalityRuntime, saveCausalMemory } from "./causality/index.js";
export { hexFingerprint as fingerprint } from "./crypto/kaalkaEngine.js";
export { decryptSessionState, encryptSessionState } from "./crypto/kaalkaSessionEngine.js";
export { loadDistributedCheckpoint, runAutonomousExtraction, saveDistributedCheckpoint } from "./distributed_extraction/index.js";
export { extractDocumentRuntime } from "./documents/universalDocumentExtractionEngine.js";
export { buildRuntimeEvolution, evolveSelectorRuntime, loadEvolutionRuntime, runEvolutionForExtraction, runEvolutionRuntime, saveEvolutionRuntime } from "./evolution_runtime/index.js";
export { buildRuntimeSandbox, executeRuntimeAction, replayRuntimeExecution, runExecutionForExtraction, simulateRuntimeExecution } from "./execution/index.js";
export { extract, extractAsync, extractDocs, extractRepo } from "./extract/pipeline.js";
export { loadBrowserIdentity, saveBrowserIdentity } from "./identity/index.js";
export { ingestInput } from "./ingestion/universalIngestionEngine.js";
export { buildInteractionGraph, extractInfiniteScroll, extractPaginatedContent, replayInteractions } from "./interaction/index.js";
export { compileUnifiedRuntimeIr } from "./ir/unifiedRuntimeIr.js";
export { RuntimeKernel, getRuntimeKernel } from "./kernel/index.js";
export { runMemoryForExtraction, runRuntimeMemory, searchRuntimeMemory } from "./memory/index.js";
export { extractMultimodal } from "./multimodal/universalMultimodalExtractionEngine.js";
export { extractNative, loadNativeRuntime, runNativeCognition, saveNativeRuntime } from "./native/index.js";
export { querySemantics } from "./query/semanticQueryEngine.js";
export { reasonSemantically } from "./reasoning/semanticReasoningEngine.js";
export { cloneRuntimeEnvironment, fabricateRuntimeReality, runReconstructionForExtraction, runReconstructionRuntime, validateReconstructedRuntime } from "./reconstruction/index.js";
export { extractRepository } from "./repository/universalRepositoryExtractionEngine.js";
export { buildRuntimeGraph, queryRuntimeGraph } from "./runtime_graph/index.js";
export { loadSemanticMemory, replaySemanticRuntime, runSemanticForExtraction, saveSemanticMemory } from "./semantic/index.js";
export { loadEncryptedSession, saveEncryptedSession } from "./session/encryptedSessionStore.js";
export { buildStreamTimeline, captureDomMutations, captureWebsocketFrames, replayStreamEvents } from "./streaming/index.js";
export { streamExtract } from "./streaming/streamingPipeline.js";
export { buildRuntimeDelta, loadSyncMemory, replaySynchronizedRuntime, runSyncForExtraction, runSynchronizedRuntime, saveSyncMemory } from "./synchronization/index.js";
export { buildRuntimeObjective, buildWorkflowPlan, loadWorkflowMemory, runWorkflowForExtraction, saveWorkflowMemory } from "./workflows/index.js";

/* ---- package-level convenience API (ported from webweavex/__init__.py) ---- */

export const version = "3.0.0";

export const __version__ = "3.0.0";

export function universalExtract(path: string): Record<string, unknown> {
  const info = ingestInput(path) as Record<string, unknown>;
  const inputType = info["input_type"];
  if (inputType === "image") {
    const multimodal = _extractMultimodal(path) as Record<string, unknown>;
    return { ingestion: info, extraction: multimodal, multimodal_ir: multimodal["multimodal_ir"] ?? {}, bounded: true };
  }
  if (inputType === "repository") {
    const repo = _extractRepositoryPath(path) as Record<string, unknown>;
    return { ingestion: info, extraction: repo, repository_ir: repo["repository_ir"] ?? {}, bounded: true };
  }
  let payload: Record<string, unknown> | null = null;
  if (inputType === "pdf") payload = extractPdfText(path) as Record<string, unknown>;
  else if (inputType === "docx") payload = extractDocxText(path) as Record<string, unknown>;
  else if (inputType === "archive") payload = extractArchive(path) as Record<string, unknown>;
  else if (inputType === "html") payload = extractHtmlFile(path) as Record<string, unknown>;
  if (payload === null) {
    return { unsupported: true, input_type: inputType, ingestion: info, bounded: true };
  }
  return { ingestion: info, extraction: payload, media_ir: compileMediaIr(payload), bounded: true };
}

export function analyze(inputData: unknown, edges: unknown = null): unknown {
  if (edges !== null && edges !== undefined) return analyzeGraph(inputData, edges);
  const result = _extract(inputData as never) as Record<string, any>;
  const graph = (result?.relationships?.execution_graph ?? {}) as Record<string, any>;
  return analyzeGraph(graph.nodes ?? [], graph.edges ?? []);
}

export function crawl(url: string, opts: Record<string, unknown> = {}): unknown {
  return _crawl(url, opts as never);
}

export async function crawlAsync(url: string, opts: Record<string, unknown> = {}): Promise<unknown> {
  return _crawl(url, opts as never);
}

export function extractRecursive(url: string, opts: Record<string, unknown> = {}): Record<string, any> {
  const crawled = _crawl(url, opts as never) as Record<string, any>;
  const out = _extract(url as never) as Record<string, any>;
  out.metadata = out.metadata ?? {};
  out.metadata.crawl = { visited: crawled?.visited ?? [], discovered: crawled?.discovered ?? [] };
  out.repository = out?.content?.repository ?? {};
  out.documents = out?.content?.documents ?? {};
  return out;
}

export function queryGraph(result: Record<string, any> | null = null, node = "", graph: Record<string, any> | null = null): unknown {
  if (graph !== null && graph !== undefined) return _queryGraphIr(graph, node);
  if (result === null || result === undefined) return _queryGraphIr({}, node);
  const g = "relationships" in result ? (result?.relationships?.execution_graph ?? {}) : result;
  return _queryGraphIr(g, node);
}

export function queryRepo(result: Record<string, any>): unknown {
  return result?.content?.repository ?? {};
}

export function queryRepository(result: Record<string, any> | null = null, source = "", path = "", opts: Record<string, any> = {}): unknown {
  if (result !== null && result !== undefined && !source) return queryRepo(result);
  return _queryRepositoryIr(source, path, opts.files);
}

export function queryKnowledge(result: Record<string, any> | null = null, entities: unknown = null, edges: unknown = null): unknown {
  if (entities !== null || edges !== null) return _queryKnowledgeIr((entities as unknown[]) ?? [], (edges as unknown[]) ?? []);
  const content = (result && typeof result === "object" ? result.content : {}) ?? {};
  return { knowledge_v2: content.knowledge_v2 ?? {}, knowledge_v18: content.knowledge_reconstruction_v18 ?? {} };
}

export function queryDocuments(result: Record<string, any> | null = null, text = ""): unknown {
  if (text) return _queryDocumentIr(text);
  if (result !== null && result !== undefined) return result?.content?.documents ?? {};
  return _queryDocumentIr("");
}

export function compileDocument(text: string): unknown {
  return compileDocumentIr(text);
}

export function compileRepository(source: string, path = "", opts: Record<string, any> = {}): unknown {
  return compileRepositoryIr(source, path, opts.files);
}
