"""Execute Python (canonical) semantic-IR closure functions; emit output + hash.
Usage: PYTHONPATH=<py2.0.1> python run_python.py fixtures.json > python_results.json
"""
import importlib
import json
import sys

from core.crypto.kaalka_hash_engine import compute_kaalka_hash as H

# fn name -> module path (canonical source location)
REGISTRY = {
    # A.1 — core.documents leaves
    "extract_rhetorical_structure": "core.documents.rhetorical_structure_engine",
    "assign_semantic_roles": "core.documents.semantic_role_engine",
    "extract_headings": "core.documents.heading_engine",
    "reconstruct_argument_dependencies": "core.documents.argument_dependency_engine",
    "resolve_coreferences": "core.documents.coreference_resolution_engine",
    # A.2 — core.semantic pressure leaves
    "compute_ambiguity_pressure": "core.semantic.ambiguity_pressure_engine",
    "compute_contradiction_pressure": "core.semantic.contradiction_pressure_engine",
    "compute_evidence_boundary_pressure": "core.semantic.evidence_boundary_pressure_engine",
    "compute_evidence_decay_pressure": "core.semantic.evidence_decay_pressure_engine",
    "compute_recursive_boundary_pressure": "core.semantic.recursive_boundary_pressure_engine",
    "compute_recursive_convergence_pressure": "core.semantic.recursive_convergence_pressure_engine",
    "compute_recursive_dependency_pressure": "core.semantic.recursive_dependency_pressure_engine",
    "compute_semantic_boundary_pressure": "core.semantic.semantic_boundary_pressure_engine",
    "compute_truth_boundary_pressure": "core.semantic.truth_boundary_pressure_engine",
    "compute_uncertainty_pressure": "core.semantic.uncertainty_pressure_engine",
    # A.2 — core.ir._base leaves
    "empty_confidence": "core.ir._base",
    "empty_lineage": "core.ir._base",
    "merge_evidence": "core.ir._base",
    # A.2 — core.graph leaves
    "model_graph_entropy": "core.graph.graph_entropy_engine",
    "detect_cycles": "core.graph.semantic_cycle_analysis_engine",
    "prove_topology": "core.graph.topology_proof_engine",
    # A.2 — core.repository leaves
    "reason_api_surface": "core.repository.api_surface_reasoning_engine",
    "reconstruct_execution_flow": "core.repository.execution_flow_engine",
    "detect_infra_signals": "core.repository.infra_semantic_engine",
    "resolve_runtime_dependencies": "core.repository.runtime_dependency_engine",
    "infer_service_interactions": "core.repository.service_interaction_engine",
    # A.2 — core.ast leaves
    "build_control_flow_graph": "core.ast.control_flow_engine",
    "reconstruct_execution_paths": "core.ast.execution_path_engine",
    "resolve_symbols": "core.ast.symbol_resolution_engine",
    # A.3 batch 1 — core.evidence trivial leaves
    "detect_authority_concentration": "core.evidence.authority_concentration_engine",
    "diffuse_authority": "core.evidence.authority_diffusion_engine",
    "resist_autonomy_erosion": "core.evidence.autonomy_erosion_engine",
    "model_causal_plurality": "core.evidence.causal_plurality_engine",
    "model_cognitive_decentralization": "core.evidence.cognitive_decentralization_engine",
    "detect_cognitive_gravity_well": "core.evidence.cognitive_gravity_engine",
    "model_cognitive_sovereignty": "core.evidence.cognitive_sovereignty_engine",
    "detect_confidence_echo": "core.evidence.confidence_echo_engine",
    "refuse_unsupported_continuity": "core.evidence.continuity_refusal_engine",
    "model_epistemic_openness": "core.evidence.epistemic_openness_engine",
    "model_evidence_decay": "core.evidence.evidence_decay_engine",
    "apply_explanatory_antigravity": "core.evidence.explanatory_antigravity_engine",
    "model_explanatory_competition": "core.evidence.explanatory_competition_engine",
    "model_explanatory_divergence": "core.evidence.explanatory_divergence_engine",
    "model_explanatory_diversity": "core.evidence.explanatory_diversity_engine",
    "detect_explanatory_fixation": "core.evidence.explanatory_fixation_engine",
    "preserve_explanatory_freedom": "core.evidence.explanatory_freedom_engine",
    "resist_explanatory_domestication": "core.evidence.explanatory_nondomestication_engine",
    "model_explanatory_self_determination": "core.evidence.explanatory_self_determination_engine",
    "refuse_inference": "core.evidence.inference_refusal_engine",
    "model_interpretive_autonomy": "core.evidence.interpretive_autonomy_engine",
    "detect_interpretive_closure": "core.evidence.interpretive_closure_engine",
    "resist_interpretive_decay": "core.evidence.interpretive_decay_engine",
    "distribute_interpretations": "core.evidence.interpretive_distribution_engine",
    "model_interpretive_divergence": "core.evidence.interpretive_divergence_engine",
    "preserve_interpretive_freedom": "core.evidence.interpretive_freedom_engine",
    "resist_interpretive_domestication": "core.evidence.interpretive_nondomestication_engine",
    "model_interpretive_self_determination": "core.evidence.interpretive_self_determination_engine",
    "apply_ontology_antigravity": "core.evidence.ontology_antigravity_engine",
    "model_ontology_boundaries": "core.evidence.ontology_boundary_engine",
    "model_ontology_competition": "core.evidence.ontology_competition_engine",
    "model_ontology_divergence": "core.evidence.ontology_divergence_engine",
    "detect_ontology_fixation": "core.evidence.ontology_fixation_engine",
    "preserve_ontology_freedom": "core.evidence.ontology_freedom_engine",
    "detect_ontology_hardening": "core.evidence.ontology_hardening_engine",
    "model_ontology_instability": "core.evidence.ontology_instability_engine",
    "ontology_limits": "core.evidence.ontology_limit_engine",
    "detect_ontology_monopoly": "core.evidence.ontology_monopoly_engine",
    "resist_ontology_domestication": "core.evidence.ontology_nondomestication_engine",
    "model_ontology_self_determination": "core.evidence.ontology_self_determination_engine",
    "resist_plurality_decay": "core.evidence.plurality_decay_engine",
    "resist_agency_decay": "core.evidence.recursive_agency_decay_engine",
    "model_recursive_agency": "core.evidence.recursive_agency_engine",
    "preserve_recursive_agency": "core.evidence.recursive_agency_preservation_engine",
    "diffuse_recursive_authority": "core.evidence.recursive_authority_diffusion_engine",
    "preserve_recursive_autonomy": "core.evidence.recursive_autonomy_preservation_engine",
    "model_capture_resistance": "core.evidence.recursive_capture_resistance_engine",
    "detect_recursive_centralization": "core.evidence.recursive_centralization_engine",
    "distribute_recursive_cognition": "core.evidence.recursive_cognitive_distribution_engine",
    "detect_recursive_coherence_inflation": "core.evidence.recursive_coherence_inflation_engine",
    "detect_recursive_confidence_echo": "core.evidence.recursive_confidence_echo_engine",
    "detect_recursive_consensus": "core.evidence.recursive_consensus_engine",
    "model_stability_boundary": "core.evidence.stability_boundary_engine",
    "model_topology_boundaries": "core.evidence.topology_boundary_engine",
    "topology_limits": "core.evidence.topology_limit_engine",
    "model_truth_boundaries": "core.evidence.truth_boundary_engine",
    "apply_worldview_antigravity": "core.evidence.worldview_antigravity_engine",
    "suppress_worldview_convergence": "core.evidence.worldview_convergence_engine",
    "model_worldview_diversity": "core.evidence.worldview_diversity_engine",
    "model_worldview_variance": "core.evidence.worldview_variance_engine",
    # A.3 batch 2 — core.evidence leaves (recursive/semantic/unsupported)
    "expose_ambiguity_visibility": "core.evidence.ambiguity_visibility_engine",
    "model_evidence_boundaries": "core.evidence.evidence_boundary_engine",
    "assess_evidence_sufficiency": "core.evidence.evidence_sufficiency_engine",
    "detect_narrative_hallucination": "core.evidence.narrative_hallucination_engine",
    "detect_recursive_drift": "core.evidence.recursive_drift_engine",
    "preserve_recursive_entropy": "core.evidence.recursive_entropy_preservation_engine",
    "track_recursive_evidence_ancestry": "core.evidence.recursive_evidence_ancestry_engine",
    "resist_exploration_decay": "core.evidence.recursive_exploration_decay_engine",
    "detect_recursive_guardianship": "core.evidence.recursive_guardianship_engine",
    "resist_independence_decay": "core.evidence.recursive_independence_decay_engine",
    "model_recursive_interpretive_independence": "core.evidence.recursive_interpretive_independence_engine",
    "detect_recursive_narrative_monopoly": "core.evidence.recursive_narrative_monopoly_engine",
    "resist_novelty_decay": "core.evidence.recursive_novelty_decay_engine",
    "model_recursive_novelty": "core.evidence.recursive_novelty_engine",
    "preserve_recursive_novelty": "core.evidence.recursive_novelty_preservation_engine",
    "detect_recursive_obedience": "core.evidence.recursive_obedience_engine",
    "recursive_ontology_limits": "core.evidence.recursive_ontology_limit_engine",
    "model_recursive_openness_stability": "core.evidence.recursive_openness_stability_engine",
    "model_recursive_phase_space": "core.evidence.recursive_phase_space_engine",
    "preserve_recursive_provenance": "core.evidence.recursive_provenance_engine",
    "recursive_reality_limits": "core.evidence.recursive_reality_limit_engine",
    "detect_recursive_self_confirmation": "core.evidence.recursive_self_confirmation_engine",
    "model_recursive_semantic_decentralization": "core.evidence.recursive_semantic_decentralization_engine",
    "distribute_recursive_semantics": "core.evidence.recursive_semantic_distribution_engine",
    "model_recursive_semantic_independence": "core.evidence.recursive_semantic_independence_engine",
    "model_sovereignty_stability": "core.evidence.recursive_sovereignty_stability_engine",
    "detect_recursive_stabilization": "core.evidence.recursive_stabilization_engine",
    "terminate_recursive_stabilization": "core.evidence.recursive_stabilization_termination_engine",
    "detect_recursive_submission": "core.evidence.recursive_submission_engine",
    "recursive_topology_limits": "core.evidence.recursive_topology_limit_engine",
    "detect_recursive_trust_monopoly": "core.evidence.recursive_trust_monopoly_engine",
    "model_recursive_truth_boundaries": "core.evidence.recursive_truth_boundary_engine",
    "refuse_recursive_stabilization": "core.evidence.recursive_truth_refusal_engine",
    "preserve_recursive_uncertainty": "core.evidence.recursive_uncertainty_preservation_engine",
    "model_semantic_alternatives": "core.evidence.semantic_alternative_engine",
    "apply_semantic_antigravity": "core.evidence.semantic_antigravity_engine",
    "model_semantic_autonomy": "core.evidence.semantic_autonomy_engine",
    "model_semantic_boundaries": "core.evidence.semantic_boundary_engine",
    "suppress_semantic_dependency": "core.evidence.semantic_dependency_suppression_engine",
    "model_semantic_divergence": "core.evidence.semantic_divergence_engine",
    "model_semantic_diversity": "core.evidence.semantic_diversity_engine",
    "detect_semantic_fixation": "core.evidence.semantic_fixation_engine",
    "model_semantic_freedom": "core.evidence.semantic_freedom_engine",
    "suppress_semantic_governance": "core.evidence.semantic_governance_engine",
    "detect_semantic_hierarchy_permanence": "core.evidence.semantic_hierarchy_engine",
    "detect_semantic_homogenization": "core.evidence.semantic_homogenization_engine",
    "measure_semantic_momentum": "core.evidence.semantic_momentum_engine",
    "resist_semantic_domestication": "core.evidence.semantic_nondomestication_engine",
    "detect_semantic_orthodoxy": "core.evidence.semantic_orthodoxy_engine",
    "model_semantic_self_determination": "core.evidence.semantic_self_determination_engine",
    "detect_semantic_self_reinforcement": "core.evidence.semantic_self_reinforcement_engine",
    "semantic_stability_limits": "core.evidence.semantic_stability_limit_engine",
    "terminate_semantic_chain": "core.evidence.semantic_termination_engine",
    "semantic_truth_limits": "core.evidence.semantic_truth_limit_engine",
    "detect_semantic_uniformity": "core.evidence.semantic_uniformity_engine",
    "detect_unsupported_expansion": "core.evidence.unsupported_expansion_engine",
    "model_unsupported_scope": "core.evidence.unsupported_scope_engine",
    # A.3 batch 3 — core.evidence medium leaves
    "apply_confidence_caps": "core.evidence.confidence_cap_engine",
    "build_contradiction_lattice": "core.evidence.contradiction_lattice_engine",
    "preserve_epistemic_boundaries": "core.evidence.epistemic_boundary_engine",
    "model_epistemic_limits": "core.evidence.epistemic_limit_engine",
    "combine_evidence": "core.evidence.evidence_algebra_engine",
    "weight_evidence_calculus": "core.evidence.evidence_weighting_calculus",
    "build_explainability": "core.evidence.explainability_engine",
    "model_inference_integrity": "core.evidence.inference_integrity_engine",
    "terminate_inference_chain": "core.evidence.inference_termination_engine",
    "preserve_instability": "core.evidence.instability_preservation_engine",
    "mark_insufficiency": "core.evidence.insufficiency_engine",
    "model_interpretive_diversity": "core.evidence.interpretive_diversity_engine",
    "build_lineage": "core.evidence.lineage_engine",
    "model_noninferable_regions": "core.evidence.noninferable_scope_engine",
    "model_noninference": "core.evidence.noninference_engine",
    "build_provenance": "core.evidence.provenance_engine",
    "model_recursive_entropy": "core.evidence.recursive_entropy_engine",
    "model_recursive_instability": "core.evidence.recursive_instability_engine",
    "preserve_recursive_lineage": "core.evidence.recursive_lineage_engine",
    "detect_speculative_coherence": "core.evidence.speculative_coherence_engine",
    "build_support": "core.evidence.semantic_support_engine",
    "build_weaknesses": "core.evidence.semantic_weakness_engine",
    "build_traceability": "core.evidence.traceability_engine",
    "refuse_unsupported_stabilization": "core.evidence.truth_refusal_engine",
    # A.3 batch 4 — final core.evidence public leaves (semantic_* heavies)
    "score_semantic_confidence": "core.evidence.semantic_confidence_engine",
    "apply_semantic_conservatism": "core.evidence.semantic_conservatism_engine",
    "assess_semantic_consistency": "core.evidence.semantic_consistency_engine",
    "model_semantic_decay": "core.evidence.semantic_decay_engine",
    "model_semantic_decentralization": "core.evidence.semantic_decentralization_engine",
    "detect_semantic_drift": "core.evidence.semantic_drift_engine",
    "model_semantic_entropy": "core.evidence.semantic_entropy_engine",
    "model_fragility": "core.evidence.semantic_fragility_engine",
    "assess_semantic_honesty": "core.evidence.semantic_honesty_engine",
    "model_incompleteness": "core.evidence.semantic_incompleteness_engine",
    "infer_from_evidence": "core.evidence.semantic_inference_calculus",
    "model_semantic_instability": "core.evidence.semantic_instability_engine",
    "build_justification": "core.evidence.semantic_justification_engine",
    "semantic_limits": "core.evidence.semantic_limit_engine",
    "detect_semantic_overreach": "core.evidence.semantic_overreach_engine",
    "model_semantic_plurality": "core.evidence.semantic_plurality_engine",
    "prove_semantic_claim": "core.evidence.semantic_proof_engine",
    "refuse_unsupported_conclusions": "core.evidence.semantic_refusal_engine",
    "apply_semantic_self_limitation": "core.evidence.semantic_self_limitation_engine",
    "model_semantic_stability": "core.evidence.semantic_stability_engine",
    "terminate_stabilization": "core.evidence.stabilization_termination_engine",
    "model_uncertainty": "core.evidence.uncertainty_engine",
    "expose_uncertainty_visibility": "core.evidence.uncertainty_visibility_engine",
    "block_unsupported_confidence_escalation": "core.evidence.unsupported_confidence_engine",
    "suppress_unsupported_inference": "core.evidence.unsupported_inference_engine",
    "preserve_recursive_divergence": "core.evidence.recursive_divergence_preservation_engine",
    "detect_recursive_domestication": "core.evidence.recursive_domestication_engine",
    # Phase B — first non-leaf layer (deps are proven Phase-A leaves only)
    "parse_python_ast": "core.ast.python_ast_engine",
    "build_argument_dependencies": "core.documents.argument_dependency_engine",
    "build_argument_graph": "core.documents.argument_graph_engine",
    "extract_instructional_flow": "core.documents.instructional_flow_engine",
    "parse_rhetorical_structure": "core.documents.rhetorical_parser_engine",
    "extract_sections": "core.documents.section_engine",
    "apply_confidence_degradation": "core.evidence.confidence_degradation_engine",
    "reason_deterministically": "core.evidence.deterministic_reasoning_engine",
    "score_epistemic_confidence": "core.evidence.epistemic_confidence_engine",
    "preserve_incompleteness": "core.evidence.incompleteness_engine",
    "model_inference_limits": "core.evidence.inference_limit_engine",
    "validate_inference": "core.evidence.inference_validation_engine",
    "apply_reality_constraints": "core.evidence.reality_constraint_engine",
    "detect_recursive_dependency": "core.evidence.recursive_dependency_engine",
    "detect_recursive_semantic_closure": "core.evidence.recursive_semantic_closure_engine",
    "detect_semantic_attractor": "core.evidence.semantic_attractor_engine",
    "_ground_parser": "core.evidence.semantic_integrity_engine",
    "detect_semantic_monoculture": "core.evidence.semantic_monoculture_engine",
    "detect_semantic_monopoly": "core.evidence.semantic_monopoly_engine",
    "score_reliability": "core.evidence.semantic_reliability_engine",
    "apply_epistemic_restraint": "core.evidence.semantic_restraint_engine",
    "propagate_uncertainty": "core.evidence.semantic_uncertainty_propagation_engine",
    "suppress_speculative_inference": "core.evidence.speculative_inference_engine",
    "propagate_uncertainty_math": "core.evidence.uncertainty_propagation_math",
    "suppress_unsupported_continuity": "core.evidence.unsupported_continuity_engine",
    "detect_unsupported_stabilization": "core.evidence.unsupported_stabilization_engine",
    "reason_topology": "core.graph.topology_reasoning_engine",
    "empty_document_ir": "core.ir.document_ir",
    "empty_repository_ir": "core.ir.repository_ir",
    "reason_api_contract": "core.repository.api_contract_reasoning_engine",
    "model_infra_relationships": "core.repository.infra_relationship_engine",
    "apply_contradiction_restraint": "core.semantic.contradiction_restraint_engine",
    # Phase C — second layer (deps are proven A/B functions)
    "compile_semantic_ast_ir": "core.ast.semantic_ast_ir_engine",
    "build_coreference_graph": "core.documents.coreference_graph_engine",
    "analyze_instructional_semantics": "core.documents.instructional_semantics_engine",
    "parse_semantic_discourse": "core.documents.semantic_discourse_parser",
    "apply_civilizational_epistemic_openness": "core.evidence.civilizational_epistemic_openness_engine",
    "apply_cognitive_anti_capture": "core.evidence.cognitive_anti_capture_engine",
    "apply_cognitive_integrity": "core.evidence.cognitive_integrity_engine",
    "apply_epistemic_civilization_stability": "core.evidence.epistemic_civilization_stability_engine",
    "apply_formal_semantic_foundation": "core.evidence.formal_semantic_foundation_engine",
    "apply_reality_bounded_confidence": "core.evidence.reality_bounded_confidence_engine",
    "apply_recursive_epistemic_sovereignty": "core.evidence.recursive_epistemic_sovereignty_engine",
    "collect_suppressed_speculation": "core.evidence.speculative_inference_engine",
    "collect_unsupported_continuity": "core.evidence.unsupported_continuity_engine",
    "reason_topology_semantic": "core.reasoning.topology_reasoning_engine",
    "analyze_deployment_semantics": "core.repository.deployment_semantics_engine",
    # Phase D — third layer (parse_source-gated engines deferred)
    "model_concept_transitions": "core.documents.concept_transition_engine",
    "apply_confidence_collapse": "core.evidence.confidence_collapse_engine",
    "apply_reality_alignment": "core.evidence.reality_alignment_engine",
    "detect_semantic_speculation": "core.evidence.semantic_speculation_engine",
    # Phase E — fourth layer (compile_repository_ir parse_source-gated, deferred)
    "build_document_dependency_graph": "core.documents.document_dependency_graph_engine",
    "model_semantic_transitions": "core.documents.semantic_transition_engine",
    "apply_cognitive_humility": "core.evidence.cognitive_humility_engine",
    "apply_recursive_confidence_decay": "core.evidence.recursive_confidence_decay_engine",
    "apply_truth_preservation": "core.evidence.truth_preservation_engine",
    # Phases F-O (document side) — final ladder to the dispatchers
    "model_concept_progression": "core.documents.concept_progression_engine",
    "apply_recursive_reality_integrity": "core.evidence.recursive_reality_integrity_engine",
    "attach_epistemic_state": "core.evidence.epistemic_evidence_engine",
    "build_semantic_integrity_object": "core.evidence.semantic_integrity_engine",
    "apply_semantic_uncertainty": "core.semantic.semantic_uncertainty_engine",
    "structure_cognition": "core.evidence.grounding_engine",
    "extract_tutorial_flow": "core.documents.tutorial_reasoning_engine",
    "reconstruct_tutorial_dependencies": "core.documents.tutorial_dependency_engine",
    "infer_tutorial_prerequisites": "core.documents.tutorial_prerequisite_engine",
    "build_document_semantic_ir": "core.documents.document_semantic_ir_engine",
    "analyze_long_range_discourse": "core.documents.long_range_discourse_engine",
    "compile_document_ir": "core.ir.document_ir",
    "query_documents": "core.query.document_query_engine",
    "reason_discourse_semantic": "core.reasoning.discourse_reasoning_engine",
    # core.parsers closure (dotted keys: attr = key after the last dot)
    "parsers.parse_source": "core.parsers.parser_registry",
    "parsers.parse_ast": "core.parsers.ast_engine",
    "parsers.recover_syntax": "core.parsers.syntax_recovery_engine",
    "parsers.enforce_budget": "core.parsers.parser_budget_engine",
    "parsers.resolve_symbols": "core.parsers.symbol_resolution_engine",
    "parsers.build_call_graph": "core.parsers.call_graph_engine",
    "parsers.resolve_imports": "core.parsers.import_resolution_engine",
    "parsers.resolve_dependencies": "core.parsers.dependency_resolution_engine",
    "parsers.resolve_runtime": "core.parsers.runtime_resolution_engine",
    "parsers.resolve_frameworks": "core.parsers.framework_resolution_engine",
    "parsers.resolve_api_surface": "core.parsers.api_resolution_engine",
    "parsers.language_capabilities": "core.parsers.parser_capability_engine",
    "parsers.build_semantic_graph": "core.parsers.semantic_graph_engine",
    "parsers.normalize_parser_output": "core.parsers.parser_output_engine",
    "parsers.require_parser_evidence": "core.parsers.formal_parser_grounding_engine",
    "parsers.build_parser_cognition_evidence": "core.parsers.parser_cognition_engine",
    "parsers.analyze_repository_source": "core.parsers.repository_semantic_engine",
    "parsers.stream_parse": "core.parsers.parser_streaming_engine",
    "ground_parser_output": "core.evidence.grounding_engine",
}


def main():
    fixtures = json.load(open(sys.argv[1], encoding="utf-8"))
    out = []
    for fx in fixtures:
        fn = fx["fn"]
        try:
            mod = importlib.import_module(REGISTRY[fn])
            attr = fn.rsplit(".", 1)[-1]
            result = getattr(mod, attr)(*fx["args"], **fx.get("kwargs", {}))
            if not isinstance(result, (dict, list, str, int, float, bool,
                                       type(None))):
                result = list(result)  # materialize generators (stream_parse)
            out.append({"id": fx["id"], "fn": fn, "output": result, "hash": H(result)})
        except Exception as e:  # noqa: BLE001
            out.append({"id": fx["id"], "fn": fn,
                        "error": f"{type(e).__name__}: {e}"})
    print(json.dumps(out, ensure_ascii=False))


if __name__ == "__main__":
    main()
